import {
  Type,
  FileText,
  Image,
  Folder,
  Database,
  Settings,
  User,
  Users,
  Mail,
  Phone,
  Calendar,
  Clock,
  MapPin,
  Link2,
  Tag,
  Bookmark,
  Star,
  Heart,
  ThumbsUp,
  MessageSquare,
  Bell,
  Search,
  Filter,
  Grid,
  List,
  Layout,
  BarChart,
  PieChart,
  TrendingUp,
  ShoppingCart,
  Package,
  Truck,
  CreditCard,
  Wallet,
  Building,
  Home,
  Globe,
  Zap,
  Lightbulb,
  Flame,
  Award,
  Trophy,
  Shield,
  Lock,
  Key,
  Eye,
  Camera,
  Video,
  Music,
  Film,
  Gamepad2,
  Coffee,
  Utensils,
  Car,
  Plane,
  Ship,
  Bike,
  // Additional icons from HTML
  Grid3x3,
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Paperclip,
  Bold,
  BookOpen,
  Briefcase,
  Paintbrush,
  Cast,
  Check,
  Cloud,
  Code,
  Cog,
  Minus,
  Command,
  Crop,
  Crown,
  MousePointer2,
  LayoutDashboard,
  Stethoscope,
  Smile,
  Frown,
  LogOut,
  Plus,
  Feather,
  File,
  FileX,
  FileSpreadsheet,
  DoorOpen,
  Gift,
  HeartHandshake,
  Hash,
  Headphones,
  Info,
  Italic,
  Mountain,
  Layers,
  Link,
  Wand2,
  Mic,
  Monitor,
  Moon,
  ArrowLeftRight,
  PaintBucket,
  Send,
  Pencil,
  PictureInPicture,
  Pin,
  Play,
  Puzzle,
  HelpCircle,
  Quote,
  RefreshCw,
  UtensilsCrossed,
  Rocket,
  RotateCw,
  Scissors,
  Sprout,
  Server,
  Shirt,
  Presentation,
  Boxes,
  Store,
  Strikethrough,
  Sun,
  Tv,
  ThumbsDown,
  Train,
  Twitter,
  Underline,
  Volume2,
  VolumeX,
  UserCircle,
  Circle,
  PenTool,
  X,
  Maximize2,
} from 'lucide-react'
import { LucideIcon } from 'lucide-react'

export interface IconItem {
  name: string
  component: LucideIcon
}

// Comprehensive icon library matching HTML reference
export const iconLibrary: IconItem[] = [
  // Basic icons
  { name: 'Type', component: Type },
  { name: 'FileText', component: FileText },
  { name: 'Image', component: Image },
  { name: 'Folder', component: Folder },
  { name: 'Database', component: Database },
  { name: 'Settings', component: Settings },
  { name: 'User', component: User },
  { name: 'Users', component: Users },
  { name: 'Mail', component: Mail },
  { name: 'Phone', component: Phone },
  { name: 'Calendar', component: Calendar },
  { name: 'Clock', component: Clock },
  { name: 'MapPin', component: MapPin },
  { name: 'Link2', component: Link2 },
  { name: 'Tag', component: Tag },
  { name: 'Bookmark', component: Bookmark },
  { name: 'Star', component: Star },
  { name: 'Heart', component: Heart },
  { name: 'ThumbsUp', component: ThumbsUp },
  { name: 'MessageSquare', component: MessageSquare },
  { name: 'Bell', component: Bell },
  { name: 'Search', component: Search },
  { name: 'Filter', component: Filter },
  { name: 'Grid', component: Grid },
  { name: 'List', component: List },
  { name: 'Layout', component: Layout },
  { name: 'BarChart', component: BarChart },
  { name: 'PieChart', component: PieChart },
  { name: 'TrendingUp', component: TrendingUp },
  { name: 'ShoppingCart', component: ShoppingCart },
  { name: 'Package', component: Package },
  { name: 'Truck', component: Truck },
  { name: 'CreditCard', component: CreditCard },
  { name: 'Wallet', component: Wallet },
  { name: 'Building', component: Building },
  { name: 'Home', component: Home },
  { name: 'Globe', component: Globe },
  { name: 'Zap', component: Zap },
  { name: 'Lightbulb', component: Lightbulb },
  { name: 'Flame', component: Flame },
  { name: 'Award', component: Award },
  { name: 'Trophy', component: Trophy },
  { name: 'Shield', component: Shield },
  { name: 'Lock', component: Lock },
  { name: 'Key', component: Key },
  { name: 'Eye', component: Eye },
  { name: 'Camera', component: Camera },
  { name: 'Video', component: Video },
  { name: 'Music', component: Music },
  { name: 'Film', component: Film },
  { name: 'Car', component: Car },
  { name: 'Plane', component: Plane },
  // Additional icons from HTML
  { name: 'apps', component: Grid3x3 },
  { name: 'archive', component: Archive },
  { name: 'arrowDown', component: ArrowDown },
  { name: 'arrowLeft', component: ArrowLeft },
  { name: 'arrowRight', component: ArrowRight },
  { name: 'arrowUp', component: ArrowUp },
  { name: 'attachment', component: Paperclip },
  { name: 'bold', component: Bold },
  { name: 'book', component: BookOpen },
  { name: 'briefcase', component: Briefcase },
  { name: 'brush', component: Paintbrush },
  { name: 'bulletList', component: List },
  { name: 'cast', component: Cast },
  { name: 'chartBubble', component: BarChart },
  { name: 'chartCircle', component: PieChart },
  { name: 'chartPie', component: PieChart },
  { name: 'check', component: Check },
  { name: 'cloud', component: Cloud },
  { name: 'code', component: Code },
  { name: 'cog', component: Cog },
  { name: 'collapse', component: Minus },
  { name: 'command', component: Command },
  { name: 'connector', component: Link2 },
  { name: 'crop', component: Crop },
  { name: 'crown', component: Crown },
  { name: 'cup', component: Coffee },
  { name: 'cursor', component: MousePointer2 },
  { name: 'dashboard', component: LayoutDashboard },
  { name: 'discuss', component: MessageSquare },
  { name: 'doctor', component: Stethoscope },
  { name: 'earth', component: Globe },
  { name: 'emotionHappy', component: Smile },
  { name: 'emotionUnhappy', component: Frown },
  { name: 'envelop', component: Mail },
  { name: 'exit', component: LogOut },
  { name: 'expand', component: Maximize2 },
  { name: 'feather', component: Feather },
  { name: 'file', component: File },
  { name: 'fileError', component: FileX },
  { name: 'filePdf', component: FileText },
  { name: 'fileXls', component: FileSpreadsheet },
  { name: 'fileZip', component: Archive },
  { name: 'fileCsv', component: FileSpreadsheet },
  { name: 'gate', component: DoorOpen },
  { name: 'gift', component: Gift },
  { name: 'handHeart', component: HeartHandshake },
  { name: 'hashtag', component: Hash },
  { name: 'headphone', component: Headphones },
  { name: 'information', component: Info },
  { name: 'italic', component: Italic },
  { name: 'landscape', component: Mountain },
  { name: 'layer', component: Layers },
  { name: 'link', component: Link },
  { name: 'magic', component: Wand2 },
  { name: 'manyToMany', component: Grid },
  { name: 'manyToOne', component: Grid },
  { name: 'manyWays', component: Grid },
  { name: 'medium', component: MessageSquare },
  { name: 'message', component: MessageSquare },
  { name: 'microphone', component: Mic },
  { name: 'monitor', component: Monitor },
  { name: 'moon', component: Moon },
  { name: 'oneToMany', component: Grid },
  { name: 'oneToOne', component: ArrowLeftRight },
  { name: 'oneWay', component: ArrowRight },
  { name: 'paint', component: PaintBucket },
  { name: 'paintBrush', component: Paintbrush },
  { name: 'paperPlane', component: Send },
  { name: 'pencil', component: Pencil },
  { name: 'picture', component: Image },
  { name: 'pin', component: Pin },
  { name: 'pinMap', component: Pin },
  { name: 'play', component: Play },
  { name: 'plus', component: Plus },
  { name: 'priceTag', component: Tag },
  { name: 'puzzle', component: Puzzle },
  { name: 'question', component: HelpCircle },
  { name: 'quote', component: Quote },
  { name: 'refresh', component: RefreshCw },
  { name: 'restaurant', component: UtensilsCrossed },
  { name: 'rocket', component: Rocket },
  { name: 'rotate', component: RotateCw },
  { name: 'scissors', component: Scissors },
  { name: 'seed', component: Sprout },
  { name: 'server', component: Server },
  { name: 'shirt', component: Shirt },
  { name: 'slideshow', component: Presentation },
  { name: 'stack', component: Boxes },
  { name: 'store', component: Store },
  { name: 'strikeThrough', component: Strikethrough },
  { name: 'sun', component: Sun },
  { name: 'television', component: Tv },
  { name: 'thumbDown', component: ThumbsDown },
  { name: 'thumbUp', component: ThumbsUp },
  { name: 'train', component: Train },
  { name: 'twitter', component: Twitter },
  { name: 'typhoon', component: Zap },
  { name: 'underline', component: Underline },
  { name: 'volumeMute', component: VolumeX },
  { name: 'volumeUp', component: Volume2 },
  { name: 'walk', component: User },
  { name: 'wheelchair', component: Circle },
  { name: 'write', component: PenTool },
]

/**
 * Get icon component by name (case-insensitive)
 * @param iconName - The name of the icon to find
 * @returns The icon component or null if not found
 */
export function getIconComponent(iconName: string | null | undefined): LucideIcon | null {
  if (!iconName) return null
  const icon = iconLibrary.find(i => i.name.toLowerCase() === iconName.toLowerCase())
  return icon ? icon.component : null
}

/**
 * Get default icon component (FileText)
 */
export function getDefaultIcon(): LucideIcon {
  return FileText
}
